# Generated by Django 5.0.6 on 2024-05-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completada',
            field=models.BooleanField(default=False),
        ),
    ]
